Add jwt authentication
stavby/michlala-fullstack-course pull request #8
Opened 2024-12-30 00:01 UTC by stavby

2024-12-30 00:02 UTC, stavby commented
Need to add tests for auth (refresh)

2025-01-03 14:03 UTC, yarondlugin requested changes

2025-01-03 14:03 UTC, yarondlugin commented on controllers/authentication.ts
> +	const { refreshToken: currentRefreshToken } = request.body;
I'd keep it as `refreshToken` since it's the refresh token that comes with the request - so that's what the user knows.
If you need to, change the new refresh token to `newRefreshToken`

2025-01-03 14:03 UTC, yarondlugin commented on controllers/authentication.ts
> +		try {
double try wtf lol

remove the outer try since it looks useles, can't think of an error that could happen there

2025-01-03 14:03 UTC, yarondlugin commented on controllers/authentication.ts
> +			const { userId, type } = jwt.verify(currentRefreshToken, jwtSecret || '') as Token;
`jwtSecret` 's type should be string so you don't have to put a default empty string everywhere

2025-01-03 14:03 UTC, yarondlugin commented on controllers/authentication.ts
> +			user.refreshTokens.push(refreshToken);
these two lines basically remove all tokens except for this one
why not just set it as a new array?
`user.refreshTokens = [refreshToken];` or something

2025-01-03 14:03 UTC, yarondlugin commented on utils/types.ts
> +export type AddUserIdToRequest<RequestType extends Request> = RequestType & { userId: string };
shouldn't the userId be inside of the body / params of the request?

2025-01-03 14:03 UTC, yarondlugin commented on utils/appConfig.ts
> +};
`...} as const`

2025-01-03 14:03 UTC, yarondlugin commented on tests/utils.ts
> +		password: 'password',
why is password hardcoded but the rest are parameters?

2025-01-03 14:03 UTC, yarondlugin commented on controllers/comments.ts
> +		const newComment = await commentModel.create({ ...data, sender: (request as AddUserIdToRequest<Request>).userId });
this pattern is kinda weird tbh

2025-01-03 14:03 UTC, yarondlugin commented on middlewares/authorization.ts
> +		const { type, userId } = jwt.verify(token, jwtSecret || '') as Token;
same here with `jwtSecret` instead of `jwtSecret || ''`

2025-01-03 14:03 UTC, yarondlugin commented on models/users.ts
> + *           description: The refresh tokens of the user.
`The currently active refresh tokens of the user`

2025-01-03 14:03 UTC, yarondlugin commented on tests/comments.test.ts
> +		const { accessToken: newAccessToken, userId: newUserId } = await login('comments-test-user', 'comments-test-user@gmail.com');
why call it "new" access token?

2025-01-03 14:03 UTC, yarondlugin commented on tests/users.test.ts
> +		const { accessToken: newAccessToken, userId: newUserId } = await login('users-test-user', 'testuser@example.com');
are you sure its ok to rely on a user you created in a previous test?

2025-01-03 15:16 UTC, stavby commented on controllers/authentication.ts
> +			user.refreshTokens.push(refreshToken);
No bro it filters the current token and adds the new one

2025-01-03 15:32 UTC, stavby commented on utils/types.ts
> +export type AddUserIdToRequest<RequestType extends Request> = RequestType & { userId: string };
this is the data we store in the request in the authentication middleware, kind of making a custom Request type

2025-01-03 15:33 UTC, stavby commented on controllers/comments.ts
> +		const newComment = await commentModel.create({ ...data, sender: (request as AddUserIdToRequest<Request>).userId });
I know but express won't accept the custom request in a middleware definition. and I've kinda given up on making it work after too long trying

2025-01-03 15:34 UTC, stavby commented on tests/comments.test.ts
> +		const { accessToken: newAccessToken, userId: newUserId } = await login('comments-test-user', 'comments-test-user@gmail.com');
changing to initial, the name "accessToken" is the global name, and we later try to refresh it so we also have an "oldAccessToken"

2025-01-03 15:35 UTC, stavby commented on tests/users.test.ts
> +		const { accessToken: newAccessToken, userId: newUserId } = await login('users-test-user', 'testuser@example.com');
It is :)

2025-01-03 15:45 UTC, yarondlugin commented on controllers/authentication.ts
> +			user.refreshTokens.push(refreshToken);
acceptable

2025-01-03 15:46 UTC, yarondlugin commented on utils/types.ts
> +export type AddUserIdToRequest<RequestType extends Request> = RequestType & { userId: string };
approved after taking a second look

2025-01-03 15:57 UTC, stavby commented on tests/utils.ts
> +		password: 'password',
same password for all test users for convenience, no need to create different ones and send it in the function

2025-01-04 16:41 UTC, yarondlugin commented on tests/utils.ts
> +		password: 'password',
legit i guess

2025-01-04 16:42 UTC, yarondlugin approved these changes

2025-01-04 16:46 UTC, merged